apiVersion: v1
kind: ConfigMap
metadata:
  name: bossnyumba-config
  namespace: bossnyumba
data:
  NODE_ENV: "production"
  LOG_LEVEL: "warn"
  ESTATE_MANAGER_API_URL: "https://api.bossnyumba.com/api/v1"
  CUSTOMER_APP_API_URL: "https://api.bossnyumba.com/api/v1"
  OWNER_PORTAL_API_URL: "https://api.bossnyumba.com/api/v1"
  ADMIN_PORTAL_API_URL: "https://api.bossnyumba.com/api/v1"
