apiVersion: v1
kind: Service
metadata:
  name: customer-app
  namespace: bossnyumba
  labels:
    app: customer-app
    app.kubernetes.io/name: customer-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: customer-app
