apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba

resources:
  - payments-deployment.yaml
  - notifications-deployment.yaml
  - reports-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: bossnyumba-platform
  app.kubernetes.io/managed-by: kustomize
