apiVersion: v1
kind: Service
metadata:
  name: owner-portal
  namespace: bossnyumba
  labels:
    app: owner-portal
    app.kubernetes.io/name: owner-portal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: owner-portal
