apiVersion: v1
kind: ConfigMap
metadata:
  name: bossnyumba-config
  namespace: bossnyumba
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_URL: "https://api.staging.bossnyumba.com/api/v1"
  POSTGRES_HOST: "postgres-service.bossnyumba.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "bossnyumba"
  REDIS_HOST: "redis-service.bossnyumba.svc.cluster.local"
  REDIS_PORT: "6379"
