apiVersion: v1
kind: Service
metadata:
  name: estate-manager
  namespace: bossnyumba
  labels:
    app: estate-manager
    app.kubernetes.io/name: estate-manager
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: estate-manager
