apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - estate-manager/deployment.yaml
  - estate-manager/service.yaml
  - customer-app/deployment.yaml
  - customer-app/service.yaml
  - owner-portal/deployment.yaml
  - owner-portal/service.yaml
  - admin-portal/deployment.yaml
  - admin-portal/service.yaml
